apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  namespace: keda-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
      - name: simple-consumer
        image: tonylixu/simple-consumer
        ports:
          - containerPort: 8090
        imagePullPolicy: Never
        args: ["java", "-jar", "target/simple-consumer-1.0.0-jar-with-dependencies.jar", "my-cluster-kafka-bootstrap.kafka:9092", "testSample", "messages"]
